# Generated by Django 4.1.3 on 2022-12-07 12:39

from django.db import migrations, models

import autoslug.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_tag_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=False, populate_from="title"),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="post_tags", to="main.tag"),
        ),
    ]
