name: Main

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

env:
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME}}
  DATABASE_USER: ${{ secrets.DATABASE_USER}}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD}}
  DATABASE_HOST: ${{ secrets.DATABASE_HOST}}
  DATABASE_PORT: ${{ secrets.DATABASE_PORT}}
  CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL}}
  CELERY_RESULT_BACKEND: ${{ secrets.CELERY_RESULT_BACKEND}}
  POST_SERVER_ITEM_ACCESS_TOKEN: ${{ secrets.POST_SERVER_ITEM_ACCESS_TOKEN }}
  EMAIL_USE_SSL: ${{ secrets.EMAIL_USE_SSL }}
  EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
  EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
  EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
  EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
  EMAIL_PORT: ${{ secrets.EMAIL_PORT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Run linters
        env:
          DJANGO_ENV: test
        run: docker-compose --file docker-compose.ci.yml run --rm api make lint
      
      - name: Run tests
        env:
          COVERAGE: true
          DJANGO_ENV: test
        run: docker-compose --file docker-compose.ci.yml run --rm api make test